/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EtRegisterCc {
        /**
          * Language
         */
        "language": string;
    }
}
declare global {
    interface HTMLEtRegisterCcElement extends Components.EtRegisterCc, HTMLStencilElement {
    }
    var HTMLEtRegisterCcElement: {
        prototype: HTMLEtRegisterCcElement;
        new (): HTMLEtRegisterCcElement;
    };
    interface HTMLElementTagNameMap {
        "et-register-cc": HTMLEtRegisterCcElement;
    }
}
declare namespace LocalJSX {
    interface EtRegisterCc {
        /**
          * Language
         */
        "language"?: string;
    }
    interface IntrinsicElements {
        "et-register-cc": EtRegisterCc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "et-register-cc": LocalJSX.EtRegisterCc & JSXBase.HTMLAttributes<HTMLEtRegisterCcElement>;
        }
    }
}
